name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: 3.11}
      
      - name: Run unit tests
        run: python -m unittest discover ./ -p "*t.py"
  
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: 3.11}
      
      - name: Run unit tests
        run: python.exe -m unittest discover ./ -p "*t.py"
